//
//  config.h
//
//
//  Created by Dirk Mika on 22.04.13.
//
//

#pragma once

//#define SHOW_FPS
//#define DEBUG_SKIP_LEVEL

#define SCREEN_W 144
#define SCREEN_H 152

#define PADDLE_X ((SCREEN_W - PADDLE_W) >> 1)
#define PADDLE_Y (SCREEN_H - PADDLE_H - 1)
#define PADDLE_H 8
#define PADDLE_W 30
#define PADDLE_START_POS GRect(PADDLE_X, PADDLE_Y, PADDLE_W, PADDLE_H)
#define PADDLE_HIDDEN_POS GRect(PADDLE_X, SCREEN_H + BALL_SIZE, PADDLE_W, PADDLE_H)
#define PADDLE_MIN_POS -2.0f
#define PADDLE_MAX_POS 116.0f
#define PADDLE_BASE_SPEED 80	// Pixel per second

#define BALL_SIZE 6
#define BALL_START_POS GRect((SCREEN_W - BALL_SIZE) / 2, SCREEN_H, BALL_SIZE, BALL_SIZE)
#define BALL_SPEED_START 50
#define BALL_SPEED_OFFSET_FAST 20
#define BALL_SPEED_OFFSET_SLOW -20
#define BALL_SPEED_OFFSET_ALL_FINISHED 10

#define BLOCK_W 16
#define BLOCK_H 10

#define POWERUP_W 15
#define POWERUP_H 9

#define MISSILE_W 3
#define MISSILE_H 8

#define INFO_TEXT_RECT GRect(0, 2, SCREEN_W, SCREEN_H)
#define HINT_TEXT_RECT GRect(4, 32, SCREEN_W - 8, SCREEN_H - 32 - PADDLE_H - 1)
#define HINT_TEXT_ABOVE_RECT GRect(4, -(SCREEN_H - 32 - PADDLE_H - 1), SCREEN_W - 8, SCREEN_H - 32 - PADDLE_H - 1)
#define BOTTOM_INFO_TEXT_RECT GRect(0, SCREEN_H, SCREEN_W, 16)

#define GAMELOOP_TIMER_INTERVALL 25  // 40 FPS

#define SCORE_AMOUNT_1UP 250

#define GAME_NUM_START_LIVES 3
#define MAX_LIVES 10

#define MAX_BALLS 4
#define MAX_BLOCKS 42
#define NUM_LEVELS 34
#define MAX_POWERUPS 4
#define MAX_MISSILES 5

#define POWERUP_BASE_SPEED 60
#define POWERUP_TIME_BALL_FAST 7000
#define POWERUP_TIME_BALL_SLOW 7000
#define POWERUP_TIME_POWER_BALL 7000
#define POWERUP_TIME_MISSILE_LAUNCHER 7000

#define MISSILE_BASE_SPEED 80
#define MISSILE_LAUNCH_DELAY 250

#define POWERUP_BAR_W 16

#define LEVEL_NUM_ROWS 11
#define LEVEL_NUM_COLS 9
#define LEVEL_DATA_BYTES_PER_ROW 5	// 4 Bit each Block = 2 Blocks per Byte

#define ANGLE_10_DEGREE 1820
#define ANGLE_45_DEGREE 8192
#define ANGLE_67_5_DEGREE 12288
#define ANGLE_160_DEGREE 29127

#define SQRT05 0.707106781186549f

#define ANIM_DUR_PADDLE_DOWN 250
#define ANIM_DUR_SHOW_STANDBY_PADDLE 500
#define ANIM_DUR_MOVE_NEXT_PADDLE_IN 750
#define ANIM_DUR_HIDE_STANDBY_PADDLE 500
#define ANIM_DELAY 50


